spring:
  batch:
    job:
      enabled: false  # 应用启动时不自动执行批处理作业
    jdbc:
      initialize-schema: always  # 自动创建批处理相关的数据库表
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080 