server:
  port: 8080

spring:
  application:
    name: spring-boot-xxl-job

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin  # XXL-JOB调度中心地址
    accessToken: default_token  # 调度中心通讯TOKEN
    executor:
      appname: ${spring.application.name}  # 执行器AppName
      address:  # 执行器注册地址，优先使用该配置
      ip:  # 执行器IP，默认为空表示自动获取
      port: 9999  # 执行器端口号
      logpath: ./xxl-job/jobhandler  # 执行器运行日志文件存储磁盘路径
      logretentiondays: 30  # 执行器日志文件保存天数 